# Generated by Django 5.2.2 on 2025-07-14 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_check',
            name='name',
        ),
        migrations.RemoveField(
            model_name='company_check',
            name='slug',
        ),
        migrations.AddField(
            model_name='company_check',
            name='company_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='app.company_check'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='rakesh', max_length=100),
        ),
    ]
