# Generated by Django 5.2.2 on 2025-07-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='rakesh', max_length=100),
        ),
    ]
