# Generated by Django 5.2.2 on 2025-07-14 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_company_check_name_remove_company_check_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_check',
            old_name='company_name',
            new_name='name',
        ),
    ]
