# Generated by Django 5.2.2 on 2025-07-15 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_notification_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='muster',
            name='company',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app.company_check'),
            preserve_default=False,
        ),
    ]
