# Generated by Django 5.2.2 on 2025-07-14 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_company_name_company_check_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_check',
            old_name='name',
            new_name='company_name',
        ),
    ]
