# Generated by Django 5.2.2 on 2025-07-14 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_name_company_check_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_check',
            old_name='company_name',
            new_name='name',
        ),
    ]
