# Generated by Django 5.2.2 on 2025-07-15 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_muster_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muster',
            name='company',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='company',
        ),
        migrations.AddField(
            model_name='leave',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave', to='app.company_check'),
        ),
    ]
