# Generated by Django 5.2.2 on 2025-07-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_company_name_company_check_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_check',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
