# Generated by Django 5.2.2 on 2025-07-16 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_task_company_alter_customuser_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='cover_picture',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='task',
            name='company',
        ),
        migrations.CreateModel(
            name='EmployeeMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, default='profile_pictures/default_profile.jpg', null=True, upload_to='profile_pictures/')),
                ('cover_picture', models.ImageField(blank=True, default='cover_pictures/default_cover.jpg', null=True, upload_to='cover_pictures/')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='app.employee')),
            ],
        ),
    ]
