# Generated by Django 5.2.2 on 2025-07-14 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_company_check_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_check',
            old_name='name',
            new_name='company_name',
        ),
    ]
