# Generated by Django 5.2.2 on 2025-07-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_task_company_alter_employee_cover_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='cover_picture',
            field=models.ImageField(blank=True, default='cover_pictures/default_cover.jpg', null=True, upload_to='cover_pictures/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default_profile.jpg', null=True, upload_to='profile_pictures/'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
