# Generated by Django 5.2.2 on 2025-07-14 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_employee_user'),
    ]

    operations = [
    ]
