# Generated by Django 5.2.2 on 2025-07-16 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_skill_employeeprofile_benefit_helpticket_payroll_and_more'),
        ('app', '0009_remove_employee_cover_picture_and_more'),
    ]

    operations = [
    ]
