# Generated by Django 5.2.2 on 2025-07-16 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_merge_20250716_1241'),
        ('app', '0010_merge_20250716_1242'),
    ]

    operations = [
    ]
