# Generated by Django 5.2.2 on 2025-07-16 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_notification_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='app.company_check'),
        ),
    ]
