# Generated by Django 5.2.2 on 2025-07-16 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_performance_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='company',
        ),
    ]
