# Generated by Django 5.2.2 on 2025-07-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_customuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, error_messages={'required': 'Name must be provided'}, max_length=100, null=True),
        ),
    ]
