# Generated by Django 5.2.2 on 2025-07-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_customuser_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='company',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
