# Generated by Django 5.2.2 on 2025-07-18 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_leave_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave', to='app.company_check'),
        ),
    ]
