# Generated by Django 5.2.2 on 2025-07-18 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_expenseclaim_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenseclaim',
            name='company',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='company',
        ),
        migrations.RemoveField(
            model_name='muster',
            name='company',
        ),
    ]
