# Generated by Django 5.2.2 on 2025-07-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_expenseclaim_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('Team Leader', 'Team Leader'), ('HR', 'HR'), ('Manager', 'Manager')], max_length=20)),
            ],
        ),
    ]
