# Generated by Django 5.2.2 on 2025-07-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_hrcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrcontact',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='hrcontact',
            name='role',
            field=models.CharField(choices=[('TL', 'Team Leader'), ('HR', 'HR'), ('MG', 'Manager')], max_length=2),
        ),
    ]
