# Generated by Django 5.2.2 on 2025-07-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_hrcontact_name_alter_hrcontact_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrcontact',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
    ]
