# Generated by Django 5.2.2 on 2025-07-24 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_hrcontact_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpDeskTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('HR_SUPPORT', 'HR Support'), ('ASSESSMENT', 'Assessment'), ('IT_SUPPORT', 'IT Support')], max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_by_tl', models.BooleanField(default=False)),
                ('viewed_by_hr', models.BooleanField(default=False)),
                ('viewed_by_manager', models.BooleanField(default=False)),
                ('escalated_to_hr_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_to_manager_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
                ('hr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_tickets', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_tickets', to=settings.AUTH_USER_MODEL)),
                ('team_leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tl_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
