# Generated by Django 5.2.2 on 2025-09-04 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_skillcategory_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillcategory',
            name='company',
        ),
    ]
