# Generated by Django 5.2.2 on 2025-07-24 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_helpdeskticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helpdeskticket',
            name='hr',
        ),
        migrations.RemoveField(
            model_name='helpdeskticket',
            name='team_leader',
        ),
        migrations.RemoveField(
            model_name='helpdeskticket',
            name='viewed_by_hr',
        ),
        migrations.RemoveField(
            model_name='helpdeskticket',
            name='viewed_by_manager',
        ),
        migrations.RemoveField(
            model_name='helpdeskticket',
            name='viewed_by_tl',
        ),
        migrations.AddField(
            model_name='helpdeskticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tl_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='helpdeskticket',
            name='category',
            field=models.CharField(choices=[('HR', 'HR Support'), ('IT', 'IT Support'), ('AS', 'Assessment')], default='HR', max_length=2),
        ),
        migrations.AddField(
            model_name='helpdeskticket',
            name='escalate_to_hr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='helpdeskticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10),
        ),
        migrations.AlterField(
            model_name='helpdeskticket',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='helpdeskticket',
            name='issue_type',
            field=models.CharField(choices=[('login', 'Login Issue'), ('email', 'Email Issue'), ('hardware', 'Hardware Issue'), ('software', 'Software Issue'), ('attendance', 'Attendance Issue'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='helpdeskticket',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
