# Generated by Django 5.2.2 on 2025-09-04 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_remove_skillcategory_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillcategory',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.company_check'),
        ),
    ]
