# Generated by Django 5.2.2 on 2025-07-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_remove_helpdeskticket_hr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='training',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='helpticket',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='training',
            name='skills',
        ),
        migrations.AddField(
            model_name='helpdeskticket',
            name='viewed_by_hr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='helpdeskticket',
            name='viewed_by_tl',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='helpdeskticket',
            name='category',
            field=models.CharField(choices=[('HR', 'HR Support'), ('IT', 'IT Support'), ('AS', 'Assessment')], max_length=2),
        ),
        migrations.DeleteModel(
            name='Benefit',
        ),
        migrations.DeleteModel(
            name='Payroll',
        ),
        migrations.DeleteModel(
            name='EmployeeProfile',
        ),
        migrations.DeleteModel(
            name='HelpTicket',
        ),
        migrations.DeleteModel(
            name='Training',
        ),
    ]
