# Generated by Django 5.2.2 on 2025-07-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_remove_employeeprofile_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpdeskticket',
            name='issue_type',
            field=models.CharField(max_length=100),
        ),
    ]
