# Generated by Django 5.2.2 on 2025-07-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_helpdeskticket_issue_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrcontact',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
