# Generated by Django 5.2.2 on 2025-07-29 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_team_created_by_alter_team_name_and_more'),
        ('app', '0031_alter_helpdeskticket_issue_type'),
    ]

    operations = [
    ]
