# Generated by Django 5.2.2 on 2025-07-29 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_hrcontact_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hrcontact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='hrcontact',
            name='name',
        ),
        migrations.AddField(
            model_name='hrcontact',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.employee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hrcontact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
