# Generated by Django 5.2.2 on 2025-07-29 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_merge_20250729_1811'),
        ('app', '0033_remove_hrcontact_email_remove_hrcontact_name_and_more'),
    ]

    operations = [
    ]
