# Generated by Django 5.2.2 on 2025-08-01 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_merge_20250729_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='helpdeskticket',
            name='category',
            field=models.CharField(choices=[('HR', 'HR Support'), ('IT', 'IT Support'), ('AS', 'Asset Support')], max_length=2),
        ),
    ]
