# Generated by Django 5.2.2 on 2025-07-31 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_merge_20250729_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='company',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app.company_check'),
            preserve_default=False,
        ),
    ]
