# Generated by Django 5.2.2 on 2025-07-31 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_chatmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='sender',
            new_name='employee',
        ),
    ]
