# Generated by Django 5.2.2 on 2025-07-31 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_rename_sender_chatmessage_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='employee',
            new_name='sender',
        ),
    ]
