# Generated by Django 5.2.2 on 2025-07-31 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_rename_employee_chatmessage_sender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
