# Generated by Django 5.2.2 on 2025-08-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_delete_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(default='2023-01-01'),
            preserve_default=False,
        ),
    ]
