# Generated by Django 5.2.2 on 2025-08-04 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_employee_user_alter_helpdeskticket_category'),
        ('app', '0040_task_start_date'),
    ]

    operations = [
    ]
