# Generated by Django 5.2.2 on 2025-08-04 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_merge_20250804_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='app.company_check'),
        ),
    ]
