# Generated by Django 5.2.2 on 2025-08-04 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_trainingtopic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingtopic',
            name='content',
        ),
        migrations.RemoveField(
            model_name='trainingtopic',
            name='description',
        ),
        migrations.RemoveField(
            model_name='trainingtopic',
            name='file',
        ),
        migrations.RemoveField(
            model_name='trainingtopic',
            name='video',
        ),
        migrations.AddField(
            model_name='trainingtopic',
            name='topic_link',
            field=models.URLField(default='1', verbose_name='Link to topic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainingtopic',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
