# Generated by Django 5.2.2 on 2025-08-05 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_timeentry_company'),
        ('app', '0043_remove_trainingtopic_content_and_more'),
    ]

    operations = [
    ]
