# Generated by Django 5.2.2 on 2025-08-05 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_merge_20250805_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPerformanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('approved_muster_count', models.IntegerField(default=0)),
                ('regular_muster_count', models.IntegerField(default=0)),
                ('leaves_taken', models.IntegerField(default=0)),
                ('remaining_leaves', models.IntegerField(default=18)),
                ('working_days', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
