# Generated by Django 5.2.2 on 2025-08-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_merge_20250805_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
    ]
