# Generated by Django 5.2.2 on 2025-08-06 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_monthlyperformancesummary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Performance',
        ),
    ]
