# Generated by Django 5.2.2 on 2025-08-06 10:32

import app.utils
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_delete_performance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='aadhar_number',
            field=app.utils.EncryptedCharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bank_account_number',
            field=app.utils.EncryptedCharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bank_name',
            field=app.utils.EncryptedCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ifsc_code',
            field=app.utils.EncryptedCharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pan_number',
            field=app.utils.EncryptedCharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pf_number',
            field=app.utils.EncryptedCharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=app.utils.EncryptedCharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?\\d{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='uan_number',
            field=app.utils.EncryptedCharField(max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='MonthlyPerformanceSummary',
        ),
    ]
