# Generated by Django 5.2.2 on 2025-08-07 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_customuser_is_first_login'),
        ('app', '0047_alter_employee_aadhar_number_and_more'),
    ]

    operations = [
    ]
