# Generated by Django 5.2.2 on 2025-08-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_merge_20250807_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='aadhar_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='pan_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='uan_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
