# Generated by Django 5.2.2 on 2025-08-07 10:40

import app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_employee_aadhar_hash_employee_pan_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bank_account_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='aadhar_number',
            field=app.utils.EncryptedCharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pan_number',
            field=app.utils.EncryptedCharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='uan_number',
            field=app.utils.EncryptedCharField(max_length=20),
        ),
    ]
